FROM highcanfly/webssh

CMD python3 run.py --debug=true --encoding="utf-8" --fbidhttp=false --hostfile="/dev/null" --origin='*' --policy=autoadd --redirect=false --syshostfile="/dev/null" --port=8888 --address=0.0.0.0
