version: '2'

services:
   django:
      restart: always
      build: .
      ports:
         - "8000:8000"
      volumes:
         - /root/.ssh:/root/.ssh # TODO: muovi in .data/
         # - .data/ssh:/root/.ssh   
         # - .data/django:/app/db_data # TODO: spostare il db in una cartella condivisa
          
   ctfd:
      image: ctfd/ctfd:latest
      user: root
      restart: always
      ports:
         - "8123:8000"
      environment:
         - DATABASE_URL=sqlite:////app/ctfd.db
         - UPLOAD_FOLDER=/app/uploads
         - LOG_FOLDER=/app/logs
      #  - REVERSE_PROXY=true
      volumes:
         - .data/ctfd:/app

   webssh:
      image: cyberhack2021pw4/webssh:latest
      restart: always
      ports:
         - "8888:8888"
      
   nginx:
      image: nginx:latest
      volumes:
         #- ./nginx:/etc/nginx/conf.d
         - ./nginx/html:/usr/share/nginx/html
      ports:
         - 80:80
      depends_on:
         - ctfd
         - django
         - webssh


networks:
    default:
    internal:
        internal: true
