version: '2'

services:
   django:
      restart: always
      build: .
      ports:
         - "8000:8000"
      volumes:
         - /root/.ssh:/root/.ssh # TODO: muovi in .data/
    
   ctfd:
      image: xsimoss/ctfd:v1.1.0
      restart: always
      ports:
         - "8123:8000"
      # TODO: in produzione usare un volume per il db
      # volumes:
      #    - .data/CTFd/ctfd.db:/opt/CTFd/CTFd/ctfd.db
      #    - .data/CTFd/logs:/var/log/CTFd
      #    - .data/CTFd/uploads:/var/uploads
      # environment:
      #    - UPLOAD_FOLDER=/var/uploads
      #    - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      #    - REVERSE_PROXY=true
      
      
   webssh:
      image: cyberhack2021pw4/webssh:latest
      restart: always
      ports:
         - "8888:8888"
      
   nginx:
      image: nginx:latest
      volumes:
         #- ./nginx:/etc/nginx/conf.d
         - ./nginx/html:/usr/share/nginx/html
      ports:
         - 80:80
      depends_on:
         - ctfd
         - django
         - webssh


networks:
    default:
    internal:
        internal: true
