# Generated by Django 2.1.15 on 2021-11-18 15:33

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacchinaAttacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Kali', max_length=120)),
                ('docker_name', models.CharField(default='cyberhack2021pw4/kali:latest', max_length=120)),
                ('descrizione', models.TextField(default='Docker Kali Predefinito')),
                ('porta_ssh_interna', models.IntegerField(default=22, validators=[app.models.validate_porta_noroot])),
                ('porta_ssh_esterna', models.IntegerField(default=4000, validators=[app.models.validate_porta_noroot])),
            ],
            options={
                'verbose_name': 'Macchina di Attacco',
                'verbose_name_plural': 'Macchine di Attacco',
            },
        ),
        migrations.RemoveField(
            model_name='sshtunnel_configs',
            name='LOCAL_PORT',
        ),
        migrations.RemoveField(
            model_name='sshtunnel_configs',
            name='REMOTE_PORT',
        ),
        migrations.AlterField(
            model_name='cyberkillchain',
            name='command_and_control',
            field=models.TextField(default='command_and_control'),
        ),
        migrations.AlterField(
            model_name='cyberkillchain',
            name='delivery',
            field=models.TextField(default='delivery'),
        ),
        migrations.AlterField(
            model_name='cyberkillchain',
            name='exfiltration',
            field=models.TextField(default='exfiltration'),
        ),
        migrations.AlterField(
            model_name='cyberkillchain',
            name='exploitation',
            field=models.TextField(default='exploitation'),
        ),
        migrations.AlterField(
            model_name='cyberkillchain',
            name='installation',
            field=models.TextField(default='installation'),
        ),
        migrations.AlterField(
            model_name='cyberkillchain',
            name='intro',
            field=models.TextField(default='intro'),
        ),
        migrations.AlterField(
            model_name='cyberkillchain',
            name='recon',
            field=models.TextField(default='recon'),
        ),
        migrations.AlterField(
            model_name='cyberkillchain',
            name='weapon',
            field=models.TextField(default='weapon'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='nome',
            field=models.CharField(default='Test', max_length=120),
        ),
        migrations.AlterField(
            model_name='lab',
            name='sotto_titolo',
            field=models.CharField(default='Test', max_length=120),
        ),
        migrations.AlterField(
            model_name='sshtunnel_configs',
            name='DNS_NAME_SERVER',
            field=models.CharField(default='localhost', max_length=220),
        ),
        migrations.AlterField(
            model_name='sshtunnel_configs',
            name='FULL_PATH_SSH_KEY',
            field=models.CharField(default='/home/ubuntu/.ssh/id_RSA', max_length=220),
        ),
        migrations.AlterField(
            model_name='sshtunnel_configs',
            name='USER_SERVER',
            field=models.CharField(default='ubuntu', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='cognome',
            field=models.CharField(default='Cognome', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', error_messages={'unique': 'Email già utilizzata'}, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(default='Nome', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pippozzo', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='professione',
            field=models.CharField(default='Professione', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', error_messages={'unique': 'Username già utilizzato'}, max_length=120, unique=True),
        ),
    ]
