# Generated by Django 2.1.15 on 2021-11-26 11:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211119_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='macchinaattacco',
            name='timer_ma',
            field=models.IntegerField(default=10800, help_text='Esempio: 3600 secondi sono 1 ora, 300 secondi sono 5 minuti', validators=[app.models.validate_flag], verbose_name='Timer sessione utente (in secondi)'),
        ),
    ]
