# Generated by Django 2.1.15 on 2021-12-02 11:53

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_macchinaattacco_timer_ma'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='ssh_pub',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=120),
        ),
    ]
