# Generated by Django 2.1.15 on 2021-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211202_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='XD3T0cbOqsFSLrTH0wPDyWjHNbdKPLIPj9nrVHjkkXywrlDwQPVZkmX8XwzOH5jj4W6t3MdQhx0m3YsBhVX5DH1bdZYYdh5eJ0fi0wJ55lcDONSmiXDcJM0', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='ssh_pub',
            field=models.CharField(default='', max_length=120),
        ),
    ]
