# Generated by Django 2.1.15 on 2021-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211202_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ssh_pub',
            new_name='ssh_pub_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='R8mWqyNUNLev0SIj62VyoZgOVoeonNtdgeiuQNAAoZ0KZ5vspLHlSfmfhC3V14v1iaoLQJqXxkjw5MVv8BOifChj1fzESnUO37jdkShJidtPIdOKzxLMqa4', max_length=120),
        ),
    ]
