# Generated by Django 2.1.15 on 2021-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211206_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSH_key_pub', models.CharField(default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Setting Server',
                'verbose_name_plural': 'Setting Server',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='37Ui5N4eosdLh6rzQdRdwHHgCo3SxSRmQUSKoBKJJlS3m1H47DmEqq1wwvXkoNasKIi7Q6U1bVWkSogPqSFpCTAoWIz53loMvmMZ61NUar7WgcJ4GuyL7tk', max_length=120),
        ),
    ]
