# Generated by Django 2.1.15 on 2021-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211206_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_server',
            name='SSH_key_pub',
        ),
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='ezg0NYD2HNcC6YYmqrexURmEQODxcoSdYgGjOreT7sBUkO3ByX4ygjUuqAkxdL8V7GUMrlbau7YssfhGdEMNy1VGC8RoVejrdMp44dkOKP3R1SM7m8QkvLd', max_length=120),
        ),
    ]
