# Generated by Django 2.1.15 on 2021-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211206_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='AjqLehHA2xIzNhM6t20wJyQRSsVEr5WsxEc6NTGniEIlwGxJ4zMQhvOy10hBytUdkzc0YCAHo3vBB6EL2TrGu5T0FqViy176B1owLXK4qjIFSxKcBrYiu4R', max_length=120),
        ),
    ]
