# Generated by Django 2.1.15 on 2021-12-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211213_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSSH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webssh_server', models.CharField(default='http://54.211.104.229:8888', max_length=120)),
            ],
            options={
                'verbose_name': 'webssh',
                'verbose_name_plural': 'webssh',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='MXubhSgMp4XYfmgEhqzsygb0OyBvM7Bl2rIdXbjVNEJ9NFFpFgberkyptpCU5i33HCZZoTCbCsKosr6rahOMbwmFVZM2lKgbBLtUDa0xQjIVbGdL4YEVElG', max_length=120),
        ),
    ]
