# Generated by Django 2.1.15 on 2021-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211214_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='professione',
        ),
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='1jfjQfnXp1aqKEj7L12x0v3joGoYyagbwsle2GxkESmWBCPGMdTSJz49Hg9u82hWPsQ4A1gUKx2aTTZTEyCfaU61Q2o33Bi9vbjNmLzzQJgTma8S4esu6HR', max_length=120),
        ),
        migrations.AlterField(
            model_name='webssh',
            name='webssh_server',
            field=models.CharField(default='http://3.89.188.106:8888', max_length=120),
        ),
    ]
