# Generated by Django 2.1.15 on 2021-12-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211214_1605'),
        ('app', '0013_auto_20211214_1447'),
    ]

    operations = [
    ]
