# Generated by Django 2.1.15 on 2021-12-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20211215_1129'),
        ('app', '0014_merge_20211215_1037'),
    ]

    operations = [
    ]
