# Generated by Django 2.1.15 on 2023-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20211215_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='pwWZKoZrROzhAAizn8nsVzuCkNis9o7ea8fUIAyEhzABc3LBB8Lhum7eqBKR20ZcQCFoW6o4b4K5ldRXRfua1sZIDSPMK585IvC0quTE4Z1UmL3aA9TF8pO', max_length=120),
        ),
    ]
