# Generated by Django 2.1.15 on 2023-09-14 14:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230914_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfd_configs',
            name='port_API',
            field=models.IntegerField(default=8123, validators=[app.models.validate_flag]),
        ),
        migrations.AlterField(
            model_name='ctfd_configs',
            name='url_API',
            field=models.CharField(default='http://tesi.simonestaiano.it', max_length=220),
        ),
        migrations.AlterField(
            model_name='user',
            name='ssh_psw',
            field=models.CharField(default='tHX111l37rxXwJhT7rgw414uaqEk5cwMdwVij3xUU38xrRCLtolHUYkMy3ngvSE0YJ6WiubnZtJzGrrxcLJnwZ2stXR6tTeY0gpHZ2WXn4eHvhKBYWP9ehu', max_length=120),
        ),
    ]
